#!/bin/sh

ALCOTEST_INPUT_PATH=$1
CTRF_OUTPUT_PATH=$2
START_TIMESTAMP=$3
END_TIMESTAMP=$4
ALCOTEST_VERSION=$5
BUILD_ROOT_PATH=$6

/action/main.exe \
    "$ALCOTEST_INPUT_PATH" \
    "$CTRF_OUTPUT_PATH" \
    "$START_TIMESTAMP" \
    "$END_TIMESTAMP" \
    "$ALCOTEST_VERSION" \
    "$BUILD_ROOT_PATH"
