name: Build and push Docker image to dockerhub
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Check out repo
      uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v4.7.0
      with:
          versionSpec: 6.8.x

    - name: Get version
      id: version
      uses: gittools/actions/gitversion/execute@v4.7.0

    - name: Remove existing tags
      run: |
        if [ $(git tag -l "v${{ env.GitVersion_FullSemVer }}") ]; then
          git tag -d v${{ env.GitVersion_FullSemVer }}
          git push --delete v${{ env.GitVersion_FullSemVer}}
        fi

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push to dockerhub
      uses: docker/build-push-action@v5
      with:
       push: true
       tags: georgejkaye/alcotest-github-action:v${{ env.GitVersion_FullSemVer }}

    - name: Update dockerhub description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: georgejkaye/alcotest-github-action

    - name: Update dockerhub tag in action yml
      run: |
        sed -i \
          "s#image: docker://georgejkaye/alcotest-github-action:v[0-9.]*#image: docker://georgejkaye/alcotest-github-action:${{ env.GitVersion_FullSemVer }}#" \
          action.yml

    - name: Commit updated action yml
      uses: EndBug/add-and-commit@v11.1.1
      with:
        add: action.yml
        message: "build: update tag"
        tag: v${{ env.GitVersion_FullSemVer }}
